name: Validate AVC .version files
on:
    push:
    pull_request:
        types:
            - reopened
            - synchronize
            - reopened

jobs:
    validate_version_files:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 1
            - name: Validate files
              uses: DasSkelett/AVC-VersionFileValidator@master
